spring:
  datasource:
    url: jdbc:mysql://hnd1.clusters.zeabur.com:31911/blog
    username: root
    password: UYV037TPkXbOc68u54t9swvpy1zK2GCq

mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 9876
